networks:
  skilla:
    name: skilla
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www
    ports:
      - "80:80"
    container_name: nginx_skilla
    networks:
      - skilla
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
    container_name: app_skilla
    networks:
      - skilla
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: skilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    container_name: db_skilla
    networks:
      - skilla